language: python
before_install:
- openssl aes-256-cbc -K $encrypted_30d6474756b2_key -iv $encrypted_30d6474756b2_iv
  -in config.enc -out ~\/.ssh/config -d
- openssl aes-256-cbc -K $encrypted_30d6474756b2_key -iv $encrypted_30d6474756b2_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
install:
- pip install flake8
python:
- '3.6'
script:
- flake8
after_success:
- ssh sp2 "cd xcz; ./auto.sh"
